name: lint-and-debug
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.173.0
      with:
        bundler: Gemfile.lock
        bundler-cache: true
        ruby-version: 2.7.1
    
    - name: Config/Versioning Debugging
      run: bundle exec jekyll doctor
    
    - name: Test Build
      run: bundle exec jekyll build
      
# Adopted from https://github.com/doamatto/nano
